import { Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Apply for a job
export const applyForJob = async (req: Request, res: Response) => {
  try {
    const { jobId } = req.params;
    const { coverLetter } = req.body;
    const userId = req.user.id;
    
    console.log('Applying for job:', jobId, 'User:', userId);
    
    // Check if job exists
    const job = await prisma.jobPost.findUnique({
      where: { id: jobId },
      include: { status: true, employer: true }
    });
    
    if (!job) {
      return res.status(404).json({ success: false, message: 'Job not found' });
    }
    
    if (job.status.status_name !== 'Open') {
      return res.status(400).json({ success: false, message: 'This job is no longer accepting applications' });
    }
    
    // Get or create seeker profile (using correct field names from your schema)
    let seeker = await prisma.jobSeekerProfile.findFirst({
      where: { user_id: userId }
    });
    
    if (!seeker) {
      console.log('Creating seeker profile for user:', userId);
      
      seeker = await prisma.jobSeekerProfile.create({
        data: {
          user_id: userId,
          full_name: 'Job Seeker',
          skills: [],
          // Remove created_at and updated_at - they should be auto-generated by Prisma
        }
      });
      console.log('Created seeker profile:', seeker.id);
    }
    
    // Check for duplicate
    const existing = await prisma.jobApplication.findFirst({
      where: {
        job_id: jobId,
        seeker_id: seeker.id
      }
    });
    
    if (existing) {
      return res.status(400).json({ success: false, message: 'You have already applied for this job' });
    }
    
    // Get pending status
    const pendingStatus = await prisma.jobApplicationStatus.findFirst({
      where: { status_name: 'Pending' }
    });
    
    if (!pendingStatus) {
      return res.status(500).json({ success: false, message: 'Application status not configured' });
    }
    
    // Create application (remove applied_at if auto-generated)
    const application = await prisma.jobApplication.create({
      data: {
        job_id: jobId,
        seeker_id: seeker.id,
        cover_letter: coverLetter || null,
        status_id: pendingStatus.id,
        // applied_at should auto-generate
      },
      include: {
        job: {
          include: { employer: true }
        },
        status: true
      }
    });
    
    console.log('Application created:', application.id);
    
    res.status(201).json({
      success: true,
      data: application,
      message: 'Application submitted successfully'
    });
  } catch (error) {
    console.error('Apply error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// Get my applications
export const getMyApplications = async (req: Request, res: Response) => {
  try {
    const userId = req.user.id;
    console.log('=== getMyApplications ===');
    console.log('User ID:', userId);
    
    const seeker = await prisma.jobSeekerProfile.findFirst({
      where: { user_id: userId }
    });
    
    if (!seeker) {
      console.log('No seeker profile - returning empty array');
      return res.status(200).json({
        success: true,
        data: [],
        count: 0
      });
    }
    
    console.log('Seeker found:', seeker.id);
    
    const applications = await prisma.jobApplication.findMany({
      where: { seeker_id: seeker.id },
      include: {
        job: {
          include: {
            employer: true,
            industry: true,
            employment_type: true
          }
        },
        status: true,
        notes: true
      },
      orderBy: { applied_at: 'desc' }
    });
    
    console.log(`Found ${applications.length} applications`);
    
    res.json({
      success: true,
      data: applications,
      count: applications.length
    });
  } catch (error) {
    console.error('Get applications error:', error);
    res.status(200).json({
      success: true,
      data: [],
      count: 0
    });
  }
};

// Get applications for employer's jobs
export const getJobApplications = async (req: Request, res: Response) => {
  try {
    const { jobId } = req.params;
    const userId = req.user.id;
    
    const employer = await prisma.employerProfile.findFirst({
      where: { user_id: userId }
    });
    
    if (!employer) {
      return res.status(404).json({ success: false, message: 'Employer profile not found' });
    }
    
    const job = await prisma.jobPost.findFirst({
      where: { id: jobId, employer_id: employer.id }
    });
    
    if (!job) {
      return res.status(404).json({ success: false, message: 'Job not found or not owned by you' });
    }
    
    const applications = await prisma.jobApplication.findMany({
      where: { job_id: jobId },
      include: {
        seeker: true,
        status: true,
        notes: {
          where: { employer_id: employer.id }
        }
      },
      orderBy: { applied_at: 'desc' }
    });
    
    res.json({ success: true, data: applications, count: applications.length });
  } catch (error) {
    console.error('Get job applications error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// Update application status
export const updateApplicationStatus = async (req: Request, res: Response) => {
  try {
    const { applicationId } = req.params;
    const { statusId, notes } = req.body;
    const userId = req.user.id;
    
    const employer = await prisma.employerProfile.findFirst({
      where: { user_id: userId }
    });
    
    if (!employer) {
      return res.status(404).json({ success: false, message: 'Employer profile not found' });
    }
    
    const application = await prisma.jobApplication.findFirst({
      where: { id: applicationId },
      include: { job: true, seeker: true }
    });
    
    if (!application || application.job.employer_id !== employer.id) {
      return res.status(404).json({ success: false, message: 'Application not found' });
    }
    
    const updatedApplication = await prisma.jobApplication.update({
      where: { id: applicationId },
      data: {
        status_id: statusId,
        employer_notes: notes || null,
        updated_at: new Date()
      },
      include: { status: true }
    });
    
    const status = await prisma.jobApplicationStatus.findUnique({
      where: { id: statusId }
    });
    
    await prisma.notification.create({
      data: {
        user_id: application.seeker.user_id,
        title: 'Application Status Updated',
        message: `Your application for ${application.job.title} has been ${status?.status_name}`,
        type: 'status_change',
        created_at: new Date()
      }
    });
    
    res.json({ success: true, data: updatedApplication, message: 'Status updated successfully' });
  } catch (error) {
    console.error('Update status error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// Add note to application
export const addApplicationNote = async (req: Request, res: Response) => {
  try {
    const { applicationId } = req.params;
    const { note } = req.body;
    const userId = req.user.id;
    
    const employer = await prisma.employerProfile.findFirst({
      where: { user_id: userId }
    });
    
    if (!employer) {
      return res.status(404).json({ success: false, message: 'Employer profile not found' });
    }
    
    const application = await prisma.jobApplication.findFirst({
      where: { id: applicationId },
      include: { job: true }
    });
    
    if (!application || application.job.employer_id !== employer.id) {
      return res.status(404).json({ success: false, message: 'Application not found' });
    }
    
    const applicationNote = await prisma.jobApplicationNote.create({
      data: {
        application_id: applicationId,
        employer_id: employer.id,
        note_text: note,
        created_at: new Date()
      }
    });
    
    res.status(201).json({ success: true, data: applicationNote, message: 'Note added successfully' });
  } catch (error) {
    console.error('Add note error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};